// responseMessage.js
module.exports = {
    NULL_VALUE: "필요한 값이 없습니다.",
    OUT_OF_VALUE: "파라미터 값이 잘못 되었습니다.",
    SIGN_UP_SUCCESS: "회원가입 성공",
    SIGN_UP_FAIL: "회원 가입 실패",
    SIGN_IN_SUCCESS: "로그인 성공",
    SIGN_IN_FAIL: "로그인 실패",
    ALREADY_ID: "존재하는 ID 입니다.",
    ALREADY_ARTICLE: "존재하는 게시글입니다",
    NO_USER: "존재하지 않는 유저 id 입니다.",
    MISS_MATCH_PW: "비밀번호가 일치하지 않습니다",

    ARTICLE_CREATE_SUCCESS: "게시글 작성 성공",
    ARTICLE_CREATE_FAIL: "게시글 작성 실패",
    ARTICLE_READ_ALL_SUCCESS: "게시글 전체 조회 성공",
    ARTICLE_READ_ALL_FAIL: "게시글 전체 조회 성공",
    ARTICLE_READ_SUCCESS: "게시글 조회 성공",
    ARTICLE_READ_FAIL: "게시글 조회 성공",
    ARTICLE_UPDATE_SUCCESS: "게시글 수정 성공",
    ARTICLE_UPDATE_FAIL: "게시글 수정 실패",
    ARTICLE_DELETE_SUCCESS: "게시글 삭제 성공",
    ARTICLE_DELETE_FAIL: "게시글 삭제 실패",
    ALREADY_ID: "존재하는 ID 입니다.",
    NO_USER: "존재하지 않는 유저 입니다.",
    NO_CATEGORY: "존재하지 않는 카테고리 입니다.",
    NO_ARTICLE: "존재하지 않는 게시물입니다.",
    MISS_MATCH_PW: "비밀번호가 일치하지 않습니다",
    LIST_READ_SUCCESS: "목록 조회 성공",
    LIST_READ_FAIL: "목록 조회 실패",
    LIST_CREATE_SUCCESS: "목록 생성 성공",
    LIST_CREATE_FAIL: "목록 생성 실패",
    REAL_TIME_SUCCESS: "실시간 급상승 게시물 검색 성공",
    RECENT_SORTING_SUCCESS: "최신순 게시물 검색 성공",
    TOP10_SORTING_SUCCESS: "Top 10 게시물 검색 성공",
    INTERNAL_SERVER_ERROR: "서버 내부 오류"
}